CREATE USER IF NOT EXISTS user@'%' IDENTIFIED BY 'user';
GRANT ALL PRIVILEGES ON *.* TO user@'%';
FLUSH PRIVILEGES;

USE `DataWarehouse`;

CREATE TABLE IF NOT EXISTS `DataWarehouse` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `plate_id` VARCHAR(15) NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `image_url` TEXT NOT NULL,
    `camera_id` VARCHAR(10) NOT NULL
);